### ISSUE TITLE
cannot import name 'ClientTwoFactorRequiredError'

### ISSUE THREAD

**Issue by insasquatchcountry** [cyb3rko/instagram-unliker#1]
Received error:
```
Traceback (most recent call last):
  File "/Users/user/INSTALOAD/instagram-unliker/1 - base/unliker.py", line 4, in <module>
    from instagram_private_api import Client, ClientError, ClientTwoFactorRequiredError
ImportError: cannot import name 'ClientTwoFactorRequiredError' from 'instagram_private_api' (/usr/local/lib/python3.11/site-packages/instagram_private_api/__init__.py)

```
I didn't know how to add the repo that you provided.
I installed instagram_private_api via pip3 on MacOS -> HomeBrew -> python3 (3.11.5)
My work around was to delete ClientTwoFactorRequiredError from line 4 and everything worked 👍

**Comment by cyb3rko** [comment]
I've used a modified version of the instagram_private_api to support MFA on Instagram. That's why the script does not find the custom files in the official library.  
Normally it should work without any installing anything, as the project files are in this repository.

But if you have found a workaround for your use-case, that's good.  
I haven't used it in a long time, happy to hear it still works :)

**Comment by cyb3rko** [comment]
FYI: I've just updated some things in this repo, you can take a look if you want.
